import { AboutContent } from "@/types/index";

export const aboutContent: AboutContent = {
  hardware: [
    {
      title: "Drone Platform",
      desc: '5" FPV Racing Drone with precision control',
    },
    {
      title: "Edge Computing",
      desc: "NVIDIA Jetson Orin Nano for real-time AI",
    },
  ],
  features: [
    {
      title: "Computer Vision",
      desc: "Real-time object detection and tracking",
    },
    {
      title: "Autonomous Flight",
      desc: "AI-powered navigation system",
    },
  ],
};
export const dataContent = [
  {
    id: 1,
    title: "Visual Data",
    description: "RGB + Depth images captured by the drone's camera.",
  },
  {
    id: 2,
    title: "LiDAR Data",
    description: "Point clouds generated by the LiDAR sensor.",
  },
  {
    id: 3,
    title: "Telemetry Data",
    description: "Radio telemetry data transmitted by the drone.",
  },
];
export const requirementsContent = [
  {
    id: 1,
    title: "Hardware Compatibility",
    description: "Ensure your hardware is compatible with the platform.",
  },
  {
    id: 2,
    title: "Sensor Calibration",
    description: "Calibrate your sensors for accurate data collection.",
  },
  {
    id: 3,
    title: "Data Format Standards",
    description: "Adhere to the specified data format standards.",
  },
];
export const guidesContent = [
  {
    id: 1,
    title: "Data Collection",
    description: "Learn how to collect data using the drone platform.",
  },
  {
    id: 2,
    title: "Data Validation",
    description: "Learn how to validate the collected data.",
  },
  {
    id: 3,
    title: "Data Submission",
    description: "Learn how to submit your data to the platform.",
  },
];
