packages:
  - 'packages/*'
  - 'apps/*'
  - 'libs/*'
onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'
  - 'nx'
  - 'sharp'
  - '@firebase/util'
  - '@parcel/watcher'
  - 'canvas'
  - 'contentlayer'
  - 'es5-ext'
  - 'onnxruntime-node'
  - 'openai-zod-to-json-schema'
  - 'protobufjs'
  - 'tree-sitter'
